### ISSUE TITLE
Support for sitecore xp 8.2

### ISSUE THREAD

**Issue by superferenabled** [Tealium/integration-sitecore#1]
Hi, just would like to know if there are plans to include support for the sitecore xp 8.2?

I installed the plugin, and everything looks fine just the methods that are supposed to inject scripts in the cshtml layout doesn't inject any code there (I mean the headInjections and bodyInjections).

if there is no planned support can I add this and send you a PR ?

**Comment by tygavin** [comment]
@superferenabled Are you saying the example code is not working?

/documentation/sample_layout.aspx

```
<% 
   var tealiumManager = TealiumFactory.TealiumManager;
   Response.Write( tealiumManager.BodyInjections().ToString() );
%>

```

**Comment by superferenabled** [comment]
I haven't tested that code but i followed the example showed in the [pdf guide](https://github.com/Tealium/integration-sitecore/blob/master/documentation/Tealium_Sitecore_Tag_Management_Module_Specification.pdf) (5pg) in the documentation folder:
![image](https://user-images.githubusercontent.com/9064733/38507847-3fdbead2-3be3-11e8-9f33-7ac72e737b2d.png)
... and this part is the one that seems not working, when i publish the project I'm not getting scripts injected, I added comments to the html but only the comments are shown:
![image](https://user-images.githubusercontent.com/9064733/38508228-37714350-3be4-11e8-8b55-06b8ad536a25.png)

I'm using .net framework 4.6 version.

**Comment by tygavin** [comment]
I see you are using cshtml.  What is your fix?  Does the following work?

```
@Html.Raw( tealiumManager.BodyInjections().ToString() )
```

**Comment by superferenabled** [comment]
Tomorrow I'll try that at the office and let you know how it goes. Thanks!

**Comment by tygavin** [comment]
Thanks for testing.  Also, feel free to submit a pull request at any time with any enhancements or fixes.

**Comment by jimmyg423** [comment]
Hi - I submitted a pull request the other day that resolves an issue with the module not rendering the default tags - also confirmed this works in Sitecore v9.0.2. I'd be happy to contribute to this module.

**Comment by tygavin** [comment]
merged pull request..  I'll also add a new package for the updates and call it version 1.0.2.3.
